### ISSUE TITLE
Build of latest with Qt5 fails in ctkErrorLogQtMessageHandler.cpp

### ISSUE THREAD

**Issue by labonny** [commontk/CTK#551]
The definition of QAtomicInt has changed from Qt4 to Qt5 and there is no longer an "operator int()" method for it in Qt5. load() / loadAcquire() should be used instead in Qt5, but these methods do not exist in Qt 4.x. 

Compile errors occur when building ctkErrorLogQtMessageHandler.cpp. Sample error (using g++ 4.8.2 on Ubuntu 14.04):
/home/rtuser/Code/ctk/CTK/Libs/Core/ctkErrorLogQtMessageHandler.cpp:70:57: error: no match for ‘operator>’ (operand types are ‘QAtomicInt’ and ‘int’)
   if (ctkErrorLogQtMessageHandler_CurrentRecursionDepth > 10)
                                                         ^

**Comment by labonny** [comment]
It looks like there is already a pull request that may contain a fix for this: https://github.com/commontk/CTK/pull/550

**Comment by finetjul** [comment]
I'll try to get the pull request soon.

**Comment by saschazelzer** [comment]
This has been fixed yesterday.

**Comment by jcfr** [comment]
:+1: Thanks @saschazelzer 

:+1:  @labonny Thanks for your report. Please, re-open the issue with this is still a problem.

**Comment by labonny** [comment]
Thanks! This works for me now.
